name: visio
description: Visio, an app for visually impaired children app.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  camera: ^0.10.3+2
  tflite_flutter: ^0.9.1
  tflite_flutter_helper: ^0.2.1
  flutter_tts: ^3.6.3
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.3
  firebase_auth: ^4.4.2
  speech_to_text: ^6.1.1
  firebase_storage: ^11.1.2
  flutter_native_splash: ^2.2.16
  intl: ^0.18.1
  path_provider: ^2.1.1
  flutter_dotenv: ^5.1.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        
  assets:
    - .env
    - assets/
    - assets/image/
    - assets/image/illustration/
    - assets/data.json


