// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHSho2ha_7VnyQxrwMAKujOh6TgVAVN20',
    appId: '1:939000884905:web:b0dc105290f865a40b43b8',
    messagingSenderId: '939000884905',
    projectId: 'seekers-df759',
    authDomain: 'seekers-df759.firebaseapp.com',
    storageBucket: 'seekers-df759.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBferQY65rf3aPTiRi_QVqwdEes5HC4m6w',
    appId: '1:939000884905:android:abd25e30d87e3b800b43b8',
    messagingSenderId: '939000884905',
    projectId: 'seekers-df759',
    storageBucket: 'seekers-df759.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkdKLefQpVlavzNuFCrLSHFQh35lib3i4',
    appId: '1:939000884905:ios:2ca95e4ae443a3960b43b8',
    messagingSenderId: '939000884905',
    projectId: 'seekers-df759',
    storageBucket: 'seekers-df759.appspot.com',
    iosClientId: '939000884905-952ljqogsg4hi9i1j90kqhak9hfdumra.apps.googleusercontent.com',
    iosBundleId: 'com.example.seekers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkdKLefQpVlavzNuFCrLSHFQh35lib3i4',
    appId: '1:939000884905:ios:2ca95e4ae443a3960b43b8',
    messagingSenderId: '939000884905',
    projectId: 'seekers-df759',
    storageBucket: 'seekers-df759.appspot.com',
    iosClientId: '939000884905-952ljqogsg4hi9i1j90kqhak9hfdumra.apps.googleusercontent.com',
    iosBundleId: 'com.example.seekers',
  );
}
